name: Smart Delivery CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker images
      run: |
        docker build -t order-service ./order-service
        docker build -t delivery-service ./delivery-service
        docker build -t tracking-service ./tracking-service
        docker build -t notification-service ./notification-service

    - name: Start Minikube
      uses: medyagh/setup-minikube@latest

    - name: Load images into Minikube
      run: |
        minikube image load order-service
        minikube image load delivery-service
        minikube image load tracking-service
        minikube image load notification-service
    - name: Create namespaces
      run: |
        kubectl apply -f k8s/namespace.yaml

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/

    - name: Verify deployments
      run: |
        kubectl get pods
        kubectl get services
